#include QMK_KEYBOARD_H

enum layers {
    COLEMAK_DH_LAYER,
    MOUSE_LAYER,
    NAVIGATION_LAYER,
    RIGHT_SYMBOLS_LAYER,
    LEFT_SYMBOLS_LAYER,
    FUNCTION_LAYER,
    NUMBERS_LAYER,
    ALWAYS_ACCESSIBLE_LAYER,
};

// clang-format off
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [COLEMAK_DH_LAYER] = LAYOUT_split_3x5_2(
    KC_Q,         KC_W,         KC_F,         KC_P,         KC_B,         KC_J,               KC_L,              KC_U,               KC_Y,               KC_SCLN,
    LSFT_T(KC_A), LT(FUNCTION_LAYER, KC_R), LT(MOUSE_LAYER, KC_S), LT(RIGHT_SYMBOLS_LAYER, KC_T), KC_G, KC_M, LT(LEFT_SYMBOLS_LAYER, KC_N), LT(NAVIGATION_LAYER, KC_E), LT(NUMBERS_LAYER, KC_I), LSFT_T(KC_O),
    KC_Z,         LCTL_T(KC_X), LALT_T(KC_C), LGUI_T(KC_D), KC_V,         KC_K,               RGUI_T(KC_H),     LALT_T(KC_COMM),    LCTL_T(KC_DOT),     KC_SLSH,
    KC_P0,        KC_BSPC,      LT(ALWAYS_ACCESSIBLE_LAYER, KC_SPC), KC_P1
  ),

  [MOUSE_LAYER] = LAYOUT_split_3x5_2(
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_BTN1, KC_WH_U, KC_BTN2, KC_TRNS,
    KC_TRNS, KC_BTN2, KC_NO,   KC_BTN1, KC_TRNS, KC_TRNS, KC_MS_L, KC_MS_D, KC_MS_U, KC_MS_R,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_WH_L, KC_WH_D, KC_WH_R, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
  ),

  [NAVIGATION_LAYER] = LAYOUT_split_3x5_2(
    KC_TRNS, KC_TRNS, KC_PGUP, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,         KC_TRNS,        KC_TRNS,
    KC_LEFT, KC_UP,   KC_DOWN, KC_RGHT, KC_TRNS, KC_TRNS, KC_LGUI, KC_NO,           LCTL(KC_LALT), LCA(KC_LSFT),
    KC_TRNS, KC_HOME, KC_PGDN, KC_END,  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,         KC_TRNS,        KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
  ),

  [RIGHT_SYMBOLS_LAYER] = LAYOUT_split_3x5_2(
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_UNDS, KC_PIPE, KC_QUOT, KC_TRNS,
    KC_CIRC, KC_ASTR, KC_AMPR, KC_NO,   KC_TRNS, KC_HASH, KC_TILD, KC_SLSH, KC_DQUO, KC_DLR,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_MINS, KC_BSLS, KC_GRV,  KC_TRNS,
    RGB_RMOD, KC_TRNS, KC_TRNS, RGB_MOD
  ),

  [LEFT_SYMBOLS_LAYER] = LAYOUT_split_3x5_2(
    KC_TRNS, KC_COLN, KC_LT,   KC_GT,   KC_SCLN, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_LCBR, KC_RCBR, KC_LPRN, KC_RPRN, KC_AT,   KC_TRNS, KC_NO,   KC_EQL,  KC_PLUS, KC_PERC,
    KC_TRNS, KC_EXLM, KC_LBRC, KC_RBRC, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_VOLD, KC_TRNS, KC_TRNS, KC_VOLU
  ),

  [FUNCTION_LAYER] = LAYOUT_split_3x5_2(
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_F7, KC_F8, KC_F9,  KC_F10,
    KC_TRNS, KC_NO,   LCTL(KC_LALT), KC_TRNS, KC_TRNS, KC_TRNS, KC_F4, KC_F5, KC_F6,  KC_F11,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_F1, KC_F2, KC_F3,  KC_F12,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
  ),

  [NUMBERS_LAYER] = LAYOUT_split_3x5_2(
    KC_PSLS, KC_7, KC_8, KC_9, KC_PPLS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_0,    KC_1, KC_2, KC_3, KC_PMNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO,   KC_TRNS,
    KC_PAST, KC_4, KC_5, KC_6, KC_PEQL, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
  ),

  [ALWAYS_ACCESSIBLE_LAYER] = LAYOUT_split_3x5_2(
    KC_TRNS, KC_TRNS, KC_COLN, KC_ESC,  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,         KC_TRNS,        KC_DEL,
    KC_TRNS, KC_PERC, KC_SLSH, KC_ENT,  KC_TRNS, DF(MOUSE_LAYER), KC_LGUI, KC_TRNS, KC_TRNS,        KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_EXLM, KC_TRNS, DF(COLEMAK_DH_LAYER), KC_TRNS, RALT_T(KC_COMM), RCTL_T(KC_DOT), QK_BOOT,
    KC_TRNS, KC_TAB,  KC_NO,   KC_TRNS
  )
};
// clang-format on
